Update CI/CD pipeline

diff --git a/.github/workflows/deploy-prep.yaml b/.github/workflows/deploy-prep.yaml
--- a/.github/workflows/deploy-prep.yaml
+++ b/.github/workflows/deploy-prep.yaml
@@ -26,6 +26,15 @@ jobs:
         with:
           path: main-repo
 
+      - name: Debug Token Presence
+        run: |
+          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
+            echo "ERROR: PAT_TOKEN is empty or not found in Secrets!"
+            exit 1
+          else
+            echo "PAT_TOKEN is present."
+          fi
+
       - name: Checkout infra-repo
         uses: actions/checkout@v4
         with:
